// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EasyScroll
{
    internal sealed partial class Vsix
    {
        public const string Id = "EasyScroll.41a51ea2-3e2c-4a41-9c84-1a18c0091579";
        public const string Name = "EasyScroll";
        public const string Description = @"Scroll smoothly through long documents using 3D editor style mouse drag controls
Controls: Hold Middle-Mouse-Click and drag through the editor";
        public const string Language = "en-US";
        public const string Version = "1.4";
        public const string Author = "Vishal Naidu";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
